# -*- coding: utf-8 -*-
"""dan1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S0mWTZPPA2cxnz8SerLWDlEofeXTzpk2
"""

#predavanje

## 1 dio

12

type(12)

# int je cijeli broj

type(12.5)

# float, decimalni broj

type("Klara"
)

#str, riječ

"APLLE"

True

False

3 > 5

7 < 2

#dictionaries {}
#list []
#tuple ()
# ( ) ne mijenjaju se
#list, mogu se mijenjati tijekom koda
# dic, dodajemo svakoj var jednu var, povezivanje dvije stvari, godine, ime, koji smjer

t=[1,2,3]

type([1,2,3])

#liste se mogu imenovati

t

plants= {"apple": "a fruit", "banana":" a herb"}

type({"apple":"a fruit", "banana": "a herb"})

plants

import pandas as pd

plants ["banana"]

pd.DataFrame(plants, [0,1])

#broji se od 0, ne od 1

squares= [ 1,4,9,16,25]

type (squares)

squares

squares[4]

squares[-2]

#ide se sa suprotne strane, zato je 16
#: od kud, do kuda se lista printa

squares[:]

squares[1:]

#od 1 nadalje

squares[1:3]

#uključuje 1 i 2, 3 neće

squares + [36,49,64,81,100]

# dodatak u listu sa +

squares

# nije zapamtio, samo je jednom zbrojio

sq2= squares + [36,49,64,81,100]

sq2

#za spremanje liste treba ime, i =

animals= ["cat", "dog", "bird"]

animals[0]

len(sq2)

#provjera dužine liste

len(sq2[:5])

#od početka do 5

letters= ["a", "b", "c", "d", "e", "f", "g"]

letters

#dodavanje između elementa 1 i 2

letters[1:2] =[1,2,3,4,5]
letters

len(letters)

#apsolutni broj

abs(1)

abs(-10)

import operator

#već programirano, lakše nam bude onda, skraćivanje koda

1 + 3

#računa sam

operator .add(1, 3)

#npr za stat je lakse, za t test ili slično

operator.sub(1,10)

operator.eq(1,10)

#nisu jednaki

#print

print(1)

#ispiše to što je u zagradi

print("this" + "" + "is" +"a"+ "full"+"sentance"  )

#treba biti razmak

print("this", "is", "a", "full", "sentance")

#ako su zarezi onda ne moramo stavljati razmak, sam skuži

print(sq2[1:5])

None

# sam je kuži, kao i is i is not

type(None)

#nema tipa

##funkcije, operacija koju radi za nas, mi ju definiramo, damo ime, mat operacija, i return result

def our_function(x) :
  """This function multiplies its argumen by 2
  written by Klara"""
  result = x*2
  return result

our_function(5)

our_function(3.14)

type(our_function)

import math

def ph(c):
  """This function calculates th pH of a solution.
  it uses the concetracion of the H+ in mol/L.
  it returns the pH."""
  ph_value = -math.log10(c)
  return ph_value

ph(0.001)

def ph1(c):
  return -math.log10(c)

ph1(0.001)

#isto je i bez return, isto napiše rezultat, ovako je za kraće funkcije

def task(x,y):
  """definicija"""
  print("this is the log10 of x", math.log10(x))
  print("this is the log10 of y", math.log10(y))
  new_number= math.log10(x)+ math.log(y)
  print("the result is below:")
  return new_number

task(1000,2.73)

def konv_eur(euro):
  dkk= euro*7.55
  return dkk

#ne zna što je euro, ali smo ga def kao broj, bitno je da budemo doslijedni u tome, nije mu bitno ime, to je više za nas

konv_eur(10)

def plus(a,b,c,d):
  suma= a + b + c + d
  return suma

plus(3,4,5,6)

# = i ==

1 == 1

# u pravom mat smislu je točno, = je ime

k= (1,2,3)

k

type(k)

width = 20
height = 5*90
height, width

width == 30

width == 20

width = 30

cp1 = 'Tomo'
cp2= ' Maria'
cp1, cp2

width == height

width = height

width == height

width

cp1 == cp2

cp1 != cp2

# != za nije jednako, dok je == za jednako

# is i is not

5 is 4

5 is 5

width is height

#ranije definirano da je tako

width is not height

#liste

squares

squares.append(36)

squares

#dodali smo 36 u listu

squares_part2= squares + [36]

squares

squares_part2

last_list =squares.copy()

last_list

squares.append(10)

last_list

squares

#append se uvijek doda na kraj, osim ako mi to sami ne napišemo

print('Participants in the course were' , cp1 , 'and', cp2 ,'.' )

# sve mora biti odvojeno zarezima

# Commented out IPython magic to ensure Python compatibility.
print('Participants in the course were %s and %s'
#   %(cp1, cp2))

sample = 'u552'

conc= 0.002
print('In a sample %s we found %s mg/L of drugs' %(sample, conc))

print (f'In a sample {sample} we found {conc} mg/L of drugs')

def bmi(w,h) :
  bmi = w/h**2
  return bmi

#**2 na kvadrat

bmi(w=60, h=1.69)

bmi(60, 1.69)

#može jedno i drugo, svejedno je

#c1 * v1 = c2 * v2

def diluter(c1=0.5 ,v1=1, v2=2):
  '''Calculating dilutions
  returns c2'''
  c2 = c1*v1/v2
  return c2

diluter(0.5,1,2)

help(diluter)

#piše nam o našoj funkciji

diluter(2)

diluter(2,1,3)

def factor_corrections(c, f=1):
  conc=c*f
  return conc

factor_corrections(0.0002, 0.01)

factor_corrections(0.0002)

def do_something_else(a=1, b=2, c=3):
  return(a,b,c,)

do_something_else()

do_something_else(10,10)

do_something_else(10,10)

do_something_else(5,5,c=5)

#isto je i ako stavimo c=5 ili samo 5 na njegovo mjesto

do_something_else(a=10)

def suma(a,b,):
  return a+b

def adding_3rd(a,b,c,):
  return suma (a,b)+ c

adding_3rd(1,2,3)

#možemo pozivati i funkcije u funkcije

#for

my_friends= ['Ivan', 'Tomo', 'Maria', 'Petar ']

my_friends

for x in my_friends:
  print (x)

def bmi(w,h):

  bmi= w/h**2
  return bmi

weights=[80,55,60,40]
heights= [1.60, 1.55, 1.70, 1.80]

for x, friend in enumerate(my_friends):
  bmi_person = bmi(weights[x], heights[x])
  print(f'{friend} had bmi of {bmi_person}')

print(f'{friend} has bmi of {bmi_person}')

#piše nam samo zadnji, to mu ostaje u memoriji

bmi_person

squares

squares= [1,4,9,16,25]

squares

for x in squares:
  print('Element is %s' %x)

for number in squares:
  print(number)

course_part =[cp1, cp2]

course_part

for name in course_part:
  print(name)

for pos in range(len(course_part)):
  print(pos)

#pos- pozicija, len-dužina

for number, element in enumerate(squares):
  print(number, element)

squares

import math

for number in squares:
  sq_root= math.sqrt(number)
  print(sq_root)

"""if else =
==
<
<=
>
=>
"""

1 <=2

# <= manje ili jednako

if 1 == 1:
  print('yes')
  print('da')
  print('oui')

1 ==2

cp1= 'Mila'
cp2= 'Marko'

if cp1== cp2:
  print('da')

if cp1 !=cp2:
  print('da')

if cp1 == cp2:
  print('da')

else:
  print('ne')

#else mora biti u razini if, inače neće biti dobro

def check_gender_by_name(name):
  if name[-1]=='a':
    gender = 'female'
  elif name[-1]== 'o':
    gender= 'male'
  else:
    gender='unknown'

  return gender

check_gender_by_name('Mila')

check_gender_by_name('Marko')

def ph(c):
  return -math.log10(c)

ph(0.001)

def ph_evaluator(c=0.001):
  'Ph decision maker'
  ph_value= ph(c)

  if ph_value < 7:
    decision='kiselo'
  else:
    decision= 'lužnato'


  return decision
ph_evaluator()

def ph_evaluator(c=0.001):

  if ph(c) < 7:
    return 'kiselo'

  else:
    return 'lužnato'
conc_list= [0.001, 0.01, 0.1, 1, 10]
for solution in conc_list:
  print(ph_evaluator(solution))

def test_if_else(a,b):

  '''a,b su argumenti
  return 'a > b' of 'a in not > b'
  '''
  if a > b:
    print(a,'>', b)

  else:
    print('%d is not > %d' %(a,b))

test_if_else(6,2)

test_if_else(2,6)

help(test_if_else)

def rectangle_area(a,b):
  '''dokumentacija'''

  A=a*b
  if a == b:
    print('kvadrat')
  else:
    print('pravokutnik')
  return A

rectangle_area(2,3)

rectangle_area

for letter in [1,2,3]:
  print('broj:' , letter)

x = 5

x

x = 7

x

#pamti ono zadnje, ne ono prije

y =2

x +y

površina= rectangle_area(5,4)

površina

(-3)**4

-(3**4)

3 * 3.75 / 1.5

a = [4,5,6]
n = [1,2,3]

x = [a,n]

x

#dobijemo matricu jednostavnu, ne spaja u jednu listu

import numpy as np

nums1 = [1,2,3,4,5]
nums1

nums2 = np.array(nums1)

type(nums2)

nums2

type(nums1)

#array može imati drugačije objekte, 1,2,3 ili 12, a,b, 45 i možemo raditi sa time, ako dodamo a prebacuje ga u string

max(nums1)

min(nums1)

np.min(nums1)

#numpy dodaje 64 inače, ne znamo što znači..

x1= np.array([1.3, 0, 2])
x1

x2= np.array([1, 0, 2])

x2

type(x1), type(x2)

x1.dtype, x2.dtype

#float- decimalni, int- cijeli

x2= np.arange(20,50,2)
x2

# 20- od koliko ide, uključen je
#50- do koliko ide, nije uključen
#2- po 2 ide, koliki je korak

np.linspace(10,20,10, endpoint=True)

np.linspace(10,20,10, endpoint=False)

nule= np.zeros((5,3))
nule.shape

np.ones((3,3))

x4 = np.random.random((3,10))

x4

import pandas as pd

pd.DataFrame(x4)

x4.dtype

x4.shape

x4.reshape(10,3)

x4.T

np.arange(2,20). reshape(2,3,3).T

I = np.eye(3)
I

I = np.eye(40)
I

A = np.arange(9).reshape(3,3)
A

A @ A

# @ za množenje matrica

