# -*- coding: utf-8 -*-
"""dan2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fJaQkVssPSm12StDzbnvfMsUN6aV94MA
"""

import numpy as np

#numeriči podaci, numerical python, nije dio osnovnog paketa, zato se zove

#matirica A- 3x3 s 9 elemenata

A= np.arange(9).reshape(3,3)

# B- 3x3 s 9 elemenata

B= np.arange(10,19).reshape(3,3)

#zbrajanje matrica

A + B

#oduzimanje

A - B

#element po element se zbraja ili oduzima

3.14 * B

#množenje matrice sa nekim brojem

3* A

#dijeljenje matrice

A/1.5

#logaritmiranje

np.log10(A)

#množenje, A * B nije isto kao A@B

A*B

#A@B- redak prve sa stupcem druge
#broj stupaca A mora biti jednak broju retka B

#prvi element u novoj matrici= 0*10 + 1 *13 + 2*16

A

B

#ove matrice se množe

#indexiranje, dohvaćanje elemenata iz strukture

#matrica 4x4, s 16 elemenata

C=np.arange(0,16).reshape(4,4)

C

#kako iz C izvući 0,5,10

#najprije retci, stupci, C[[retci, stupci]], brojenje kreće od 0

C[[0,1,2],[0,1,2]]

#duple zagrade kada dohvaćamo više elemenata

#iz matrice 13 izvući

C[3,1]

#matrica vizualni prikaz

import matplotlib.pyplot as plt

plt.imshow(C)

#maske- izdvajanje elemenata koji zadovoljavaju uvjete

C

#gdje je <5 da piše true

bools= C < 5
bools

#bools- ime maske

#primjeniti na C

C[bools]

#indexiranje

#iz matrice C želimo odvojiti samo 3 redak

C[2]

#želimo izdvojiti vrijednost 2 redak, 2 stupac

C[1,1]

#svi retci osim zadnjeg, svi stupci osim zadnjeg, dvotočka je za raspon, od:do, kada nema dvotočke uzimaju se svi elementi

C[:-1, :-1]

#svi elementi 2 i 3 stupca

C[:, 1:3]

C[:, [1,2]]

C[:,[0,-1]]

#elementi prve i zadnje kolone

# 4 i 5 iz matrice A

A[1,[1,2]]
A[1,1:3]
A[[1,1],[1,2]]

A

#plot a bit

import matplotlib.pyplot as plt

#stvaramo dvije list i prikažemo ih grafički

seq=[5,8,2,6,1,8,2,3,20,5,6,]
seq2=[1,8,3,4,5,8,2,10,4,5,7,]

plt.plot(seq)

#vrijednosti seq list su na y

#scatter, zahtijeva definiranje osi, gleda x, ali mu fali y

plt.scatter(x=seq, y=seq2)

fig, ax = plt.subplots(figsize=(5,5))
ax.scatter(x=seq, y=seq2, c='blue', s=100, marker='2')
plt.title('Moj graf')
plt.xlabel('x os')
plt.ylabel('y os')
plt.show()

C

C[:,3].shape, C[:,[3]].shape

#prvo je jedan stupac izvučen kao 1d niz, to je vektor, nema inf o stupcu

#drugo- uzmi sve retke i stupac 0, ali kao listu, imamo inf o stupcu

#pomoću matirce C naapravi scatter plot, x os prvi stupac vrijednosti, y vrijednosti zaddnjeg stupca

plt.scatter(x=C[:,[0]], y=C[:,3], c='red', s=100, marker='3')
plt.show()

#prikaži sliku matice C

plt.imshow(C)

#back naredba- crl + Z

#uzmi matricu C, izračunaj log10 svakog elementa i prikaži rezultat kao sliku

plt.imshow(np.log10(C))

#aggregation

#preimenovanje c u a

A=C

A

#najniža vrijednost u a

np.min(A)

A.min()

#najveća vrijednost

A.max()

#st dev elemenata 1 i 2 stupca

A[:, 0:2].std()

C

#ispiši najmanju vrijednost svakog retka iz matice A

#0- vertical, 1 horizontal

A

A.min(axis=1)

#ispiši najvišu vrijednost svakog stupca A

A.max(axis=0)

#zbroji sve vrijednosti po stupcima

A.sum(axis=0)

#izračunaj st dev po stupcima i zbroji ih

A.std(axis=0).sum()

#task- matrica 4,4, sum of first colum, get variance of 2nd column

#linearna algebra

A

B

#jed matrica 3x3, jedinice po dijagonali, ostalo su 0

I=np.eye(3)

I

#dot product- dobije se sa @

#matica D, 3x3, s 9 nasumičnih brojeva

D=np.random.random(9).reshape(3,3)

D

#inverzna matrica- matrica koju kada množimo s izvornom matircom daje jediničnu

np.linalg.inv(D)

#provjera

D @ np.linalg.inv(D)

